apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: hashicorp/http-echo
          args:
            - "-text=Hello from DC A com metal lb A"
          ports:
            - containerPort: 5678
          resources:
            requests:
              cpu: "100m" # 0.1 vCPU
              memory: "128Mi" # 128 MB
            limits:
              cpu: "500m" # 0.5 vCPU
              memory: "256Mi" # 256 MB
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: 5678
