apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-health-database
  labels:
    app: demo-health-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-health-database
  template:
    metadata:
      labels:
        app: demo-health-database
    spec:
      containers:
        - name: demo-health-database
          image: thalessantanna/demo-health-database:latest
          ports:
            - containerPort: 30001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: DB_HOST
              value: host.minikube.internal
            - name: DB_USER
              value: user
            - name: DB_PASS
              value: pass
            - name: DB_DATABASE
              value: mydb
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 30001
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 30001
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: demo-health-database-service
spec:
  type: LoadBalancer
  selector:
    app: demo-health-database
  ports:
    - port: 80
      targetPort: 30001
