apiVersion: v1
kind: Pod
metadata:
  name: nettest
spec:
  containers:
    - name: nettest
      image: busybox:1.35
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: "100m" # 0.1 vCPU
          memory: "128Mi" # 128 MB
        limits:
          cpu: "500m" # 0.5 vCPU
          memory: "256Mi" # 256 MB

# kubectl apply -f pod.yaml
# kubectl exec -it nettest -- sh
